project:
  type: website
  output-dir: _site

website:
  navbar:
    title: false
    background: "#9088A4"
    foreground: "#F5F3EF"
    logo: assets/ukri-drsc-logo-transparent.png
    logo-alt: Logo for the UKRI Digital Research Skills Catalyst
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: consult.qmd
        text: Consult an Expert
      - href: news.qmd
        text: News &amp; Events
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact
  page-footer:
    background: "#9088A4"
    foreground: "#F5F3EF"
    left:
      - text: contact
        href: https://fusion-cdt.ac.uk/about/contact/
      - text: accessibility
        href: "https://www.york.ac.uk/about/legal-statements/accessibility/"
      - text: privacy
        href: "https://www.york.ac.uk/about/legal-statements/#privacy"
      - text: cookies
        href: "https://www.york.ac.uk/about/legal-statements/cookies/"
      - text: funding
        href: "#"
    right:
      - icon: linkedin
        href: https://uk.linkedin.com/company/ukri-digital-research-skills-catalyst
      - icon: bluesky
        href: https://bsky.app/profile/ukriskillscatalyst.bsky.social
format:
  html:
    page-layout: full
    theme: cosmo
    css: style.css
    code-fold: true
